name: build

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t imock .
    - name: Test using the built Docker image
      run: |
        mkdir output && \
        docker run \
          --mount "type=bind,source=$PWD/output,target=/IMock/output" \
          -t imock \
          bash -c "make test-all && mv lcov.info output"
    - name: Upload test coverage to codecov
      uses: codecov/codecov-action@v3
