name: build

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test using Docker
      run: echo "$(bash <(curl -s https://codecov.io/env))" && docker build -t imock . && docker run \
        $(bash <(curl -s https://codecov.io/env)) \
        -e CI=true \
        -t imock \
        bash -c "make test-all && /codecov"
