name: build

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t imock .
    - name: Test using the built Docker image
      run: |
        mkdir output && \
        docker run \
          --mount "type=bind,source=$PWD/output,target=/IMock/output" \
          -t imock \
          bash -c "make test-all && mv lcov.info output"
    - name: Upload test coverage to codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov && \
          chmod +x ./codecov && \
          ./codecov -f output/lcov.info -t ${CODECOV_TOKEN}

#      run: echo "$(bash <(curl -s https://codecov.io/env))" && docker build -t imock . && docker run \
#        $(bash <(curl -s https://codecov.io/env)) \
#        -e CI=true \
#        -t imock \
#        bash -c "make test-all && /codecov"
