name: build

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test using Docker
      run: |
        ci_env=`bash <(curl -s https://codecov.io/env)` |
        docker build -t imock . && docker run -t imock $ci_env -e CI=true bash \
          bash -c "make test-all && /codecov"
